In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
import seaborn as sns

In [3]:
train = pd.read_csv('criminal_train.csv')
test = pd.read_csv('criminal_test.csv')

In [4]:
Y = train['Criminal']
train = train.drop(['PERID','Criminal'],axis=1)

In [5]:
from sklearn.model_selection import train_test_split


In [6]:
train.head()

IFATHER  NRCH17_2  IRHHSIZ2  IIHHSIZ2  IRKI17_2  IIKI17_2  IRHH65_2  \
0        4         2         4         1         3         1         1   
1        4         1         3         1         2         1         1   
2        4         1         2         1         2         1         1   
3        4         0         2         1         1         1         1   
4        1         0         6         1         4         1         1   

   IIHH65_2  PRXRETRY  PRXYDATA  ...    POVERTY3  TOOLONG  TROUBUND  PDEN10  \
0         1        99        99  ...           2        1         2       1   
1         1        99        99  ...           1        2         2       2   
2         1        99        99  ...           1        2         2       2   
3         1        99        99  ...           3        2         2       1   
4         1        99         1  ...           1        2         2       2   

   COUTYP2  MAIIN102  AIIND102     ANALWT_C  VESTR  VEREP  
0        1         2         2  3884.805998  40026      1  
1        3         2         2  1627.108106  40015      2  
2        3         2         2  4344.957980  40024      1  
3        1         2         2   792.521931  40027      1  
4        2         2         2  1518.118526  40001      2  

[5 rows x 70 columns]

In [7]:
X = pd.DataFrame(train)
y = Y

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
dtree = DecisionTreeClassifier()

In [10]:
dtree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
predictions = dtree.predict(X_test)

In [13]:
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

[[12284   466]
 [  417   549]]
             precision    recall  f1-score   support

          0       0.97      0.96      0.97     12750
          1       0.54      0.57      0.55       966

avg / total       0.94      0.94      0.94     13716



In [14]:
from sklearn.ensemble import RandomForestClassifier as RFC

In [15]:
rfc = RFC(n_estimators=200)

In [16]:
rfc.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [18]:
rfc_pred = rfc.predict(X_test)

In [20]:
print(confusion_matrix(Y_test,rfc_pred))
print(classification_report(Y_test,rfc_pred))

[[12488   262]
 [  417   549]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.97     12750
          1       0.68      0.57      0.62       966

avg / total       0.95      0.95      0.95     13716



In [21]:
Z = test['PERID']

In [22]:
test = test.drop(['PERID'],axis=1)

In [24]:
predict_final = rfc.predict(test)

In [25]:
predict_final

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
submiss = pd.DataFrame()
submiss['PERID'] = Z

submiss['Criminal'] = predict_final
submiss.head()

PERID  Criminal
0  66583679         0
1  35494679         0
2  79424679         0
3  11744679         0
4  31554679         0

In [27]:
submiss[['PERID','Criminal']]

PERID  Criminal
0      66583679         0
1      35494679         0
2      79424679         0
3      11744679         0
4      31554679         0
5      83164679         0
6      58474679         0
7      40695779         0
8      39315779         0
9      58415779         0
10     23535779         0
11     67275779         0
12     93485779         0
13     29546779         0
14     97556779         0
15     37797779         0
16     36607779         0
17     61727779         0
18     20827779         0
19     52437779         0
20     87267779         0
21     33287779         0
22     30398779         0
23     98598779         0
24     41818779         1
25     69638779         0
26     25748779         0
27     75368779         0
28     99968779         0
29     91578779         0
...         ...       ...
11400  43750730         1
11401  35360730         0
11402  51380730         0
11403  50480730         0
11404  71901730         0
11405  96021730         0
11406  71331730         0
11407  66541730         0
11408  29861730         0
11409  95071730         0
11410  61281730         0
11411  57202730         0
11412  45402730         0
11413  45022730         0
11414  99432730         0
11415  26732730         0
11416  85832730         0
11417  45782730         0
11418  26493730         0
11419  54693730         0
11420  97103730         0
11421  99713730         0
11422  74543730         0
11423  57863730         0
11424  97294730         0
11425  31894730         0
11426  98524730         0
11427  80134730         0
11428  65323398         0
11429  90906563         0

[11430 rows x 2 columns]

In [28]:
submiss.columns

Index(['PERID', 'Criminal'], dtype='object')

In [29]:
submiss.to_csv('crim2_final.csv',index=False)